# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Go app to Azure Web App - bechamel-api

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - jr/add-nix
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install nix and build
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --command "go mod download"
      - run: nix-shell --command "go build ."

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: go-app
          path: ./bechamel-api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'jroemer'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: go-app

      - name: 'Deploy to Azure Web App'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}